force-app/main/default/objects/Appraisal_Cycles__mdt.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Cycle_Name__c</fullName>
        <label>Appraisal Cycle Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>Appraisal Cycles</label>
    <pluralLabel>Appraisal Cycles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AppraisalCycle__c</fullName>
        <label>Appraisal Cycle</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Appraiser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Appraiser</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Employee Master (Appraiser)</relationshipLabel>
        <relationshipName>Employee_Master1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Band__c</fullName>
        <label>Band</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Band B</fullName>
                </value>
                <value>
                    <fullName>Band C</fullName>
                </value>
                <value>
                    <fullName>Band E</fullName>
                </value>
                <value>
                    <fullName>Band M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Designation__c</fullName>
        <label>Designation</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Band__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>ASSOCIATE CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>ASSOCIATE DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>ASSOCIATE MANAGER</fullName>
                </value>
                <value>
                    <fullName>AVP(ASSOCIATE VICE PRESIDENT)</fullName>
                </value>
                <value>
                    <fullName>CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>DIRECTOR - HUMAN RESOURCES</fullName>
                </value>
                <value>
                    <fullName>EXECUTIVE</fullName>
                </value>
                <value>
                    <fullName>EXECUTIVE VP</fullName>
                </value>
                <value>
                    <fullName>GROUP PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>GROUP QA MANAGER</fullName>
                </value>
                <value>
                    <fullName>INDUSTRY PRINCIPAL</fullName>
                </value>
                <value>
                    <fullName>LEAD CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>MANAGEMENT TRAINEE</fullName>
                </value>
                <value>
                    <fullName>MANAGER</fullName>
                </value>
                <value>
                    <fullName>PRINCIPAL CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>PRINCIPAL TECHNOLOGY ARCHITECT</fullName>
                </value>
                <value>
                    <fullName>PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>QA LEAD</fullName>
                </value>
                <value>
                    <fullName>QA MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>SENIOR DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>SENIOR EXECUTIVE</fullName>
                </value>
                <value>
                    <fullName>SENIOR INDUSTRY PRINCIPAL</fullName>
                </value>
                <value>
                    <fullName>SENIOR LEAD CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>SENIOR MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR QA LEAD</fullName>
                </value>
                <value>
                    <fullName>SENIOR QA MANAGER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Employee Master (Reviewer)</relationshipLabel>
        <relationshipName>Employee_Master2</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>AppraisalCycle__c</fullName>
        <label>Appraisal Cycle</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AppraiserFeedback__c</fullName>
        <label>Appraiser Feedback</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AppraiserRating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Appraiser Rating</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EmployeeMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Master</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Not Initiated</fullName>
                </value>
                <value>
                    <fullName>Pending with Reviewer</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submitted by Appraiser</fullName>
                </value>
                <value>
                    <fullName>Final Rating Available</fullName>
                </value>
                <value>
                    <fullName>Grievance Raised</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Auto Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Appraiser_Weightage_for_Each_KPIs__c</fullName>
        <label>Appraiser Weightage for Each KPIs</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Band__c</fullName>
        <label>Band</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Band B</fullName>
                </value>
                <value>
                    <fullName>Band C</fullName>
                </value>
                <value>
                    <fullName>Band E</fullName>
                </value>
                <value>
                    <fullName>Band M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Designation__c</fullName>
        <label>Designation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASSOCIATE CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>ASSOCIATE DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>ASSOCIATE MANAGER</fullName>
                </value>
                <value>
                    <fullName>AVP(ASSOCIATE VICE PRESIDENT)</fullName>
                </value>
                <value>
                    <fullName>CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>DIRECTOR - HUMAN RESOURCES</fullName>
                </value>
                <value>
                    <fullName>EXECUTIVE</fullName>
                </value>
                <value>
                    <fullName>EXECUTIVE VP</fullName>
                </value>
                <value>
                    <fullName>GROUP PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>GROUP QA MANAGER</fullName>
                </value>
                <value>
                    <fullName>INDUSTRY PRINCIPAL</fullName>
                </value>
                <value>
                    <fullName>LEAD CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>MANAGEMENT TRAINEE</fullName>
                </value>
                <value>
                    <fullName>MANAGER</fullName>
                </value>
                <value>
                    <fullName>PRINCIPAL CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>PRINCIPAL TECHNOLOGY ARCHITECT</fullName>
                </value>
                <value>
                    <fullName>PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>QA LEAD</fullName>
                </value>
                <value>
                    <fullName>QA MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>SENIOR DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>SENIOR EXECUTIVE</fullName>
                </value>
                <value>
                    <fullName>SENIOR INDUSTRY PRINCIPAL</fullName>
                </value>
                <value>
                    <fullName>SENIOR LEAD CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>SENIOR MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR QA LEAD</fullName>
                </value>
                <value>
                    <fullName>SENIOR QA MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR QUALITY ANALYST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EmployeeMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Master</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Task tracker (Employee Master)</relationshipLabel>
        <relationshipName>Task_tracker2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee_ID__c</fullName>
        <label>Employee ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evaluation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluation</label>
        <referenceTo>Evaluation__c</referenceTo>
        <relationshipLabel>Task tracker</relationshipLabel>
        <relationshipName>Task_tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Testing In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing completed</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task Tracker</label>
    <nameField>
        <displayFormat>TQ-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CCT_AppraiserController_Test.cls
@isTest
public without sharing class CCT_AppraiserController_Test {
    
    /**
* @description Method to setup the test data.
*/
    @TestSetup
    public static void setup(){
        Account acc=new Account();
        acc.Name='Claudtaru';
        insert acc;
        
        PU_DU__c profitunit=new PU_DU__c();
        profitunit.No_of_Employees_In_This_PU__c = 20;
        profitunit.name = 'PU';
        String recordTypeIdpudu =Schema.SObjectType.PU_DU__c.getRecordTypeInfosByName().get('PU').getRecordTypeId();
        profitunit.RecordTypeId=RecordTypeIdpudu;
        insert profitunit;
        
        PU_DU__c du1=new PU_DU__c();
        du1.Name='DU1';
        du1.Profit_Unit__c = profitunit.id;
        String recordTypeIdpudu1 =Schema.SObjectType.PU_DU__c.getRecordTypeInfosByName().get('DU').getRecordTypeId();
        du1.RecordTypeId = RecordTypeIdpudu1;
        du1.No_of_Employees_In_This_DU__c=10;
        insert du1;
        
        Id recordTypeIdCandidate =Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Candidate').getRecordTypeId();
        
        Contact empl=new Contact();
        empl.AccountId=acc.Id;
        empl.Salutation='Mr.';
        empl.FirstName='Syamala';
        empl.LastName='Siri';
        empl.RecordTypeId=recordTypeIdCandidate;
        empl.Active__c=true;
        empl.Employee_Joining_Date__c=date.today().addMonths(-10);
        empl.Role__c='HR';
        empl.EmployeeNo__c='CT-0124';
        empl.Employee_State__c='Andhra Pradesh';
        empl.Aadhar_Number__c='175623209834';
        empl.Account_Number__c='123556889987';
        empl.Employee_Id__c='CT-8746';
        empl.IFSC_Code__c='SBIN0123457';
        empl.MobilePhone='8614123124';
        empl.Phone='7614123124';
        empl.PAN_Number__c='MJAPS1145H';
        empl.PU_DU__c=du1.id;
        empl.Email='gouthamboini@gmail.com';
        empl.Designation__c = 'None';
        empl.Band__c = 'Band C';
        
        insert empl;
        
        Contact emp=new Contact();
        emp.AccountId=acc.Id;
        emp.Salutation='Mr.';
        emp.FirstName='Vignesh';
        emp.LastName='Shrinivas';
        emp.Active__c=true;
        emp.Employee_Joining_Date__c=date.today().addMonths(-10);
        emp.Role__c='HR';
        emp.EmployeeNo__c='CT-0123';
        emp.Employee_State__c='Andhra Pradesh';
        emp.Aadhar_Number__c='145623209838';
        emp.Account_Number__c='123456889987';
        emp.Employee_Id__c='CT-8745';
        emp.IFSC_Code__c='SBIN0123456';
        emp.MobilePhone='9614123124';
        emp.Phone='9614123124';
        emp.PAN_Number__c='MJAPS1145J';
        emp.PU_DU__c=du1.id;
        emp.Email='guestuser@gmail.com';
        emp.Designation__c = 'None';
        emp.Band__c = 'Band C';
        emp.Appraiser__c = empl.Id;
        emp.Reviewer__c = empl.Id;
        insert emp;
        
        Contact emp1=new Contact();
        emp1.AccountId=acc.Id;
        emp1.Salutation='Mr.';
        emp1.FirstName='Vignesh';
        emp1.LastName='Shrinivas';
        emp1.Active__c=true;
        emp1.Employee_Joining_Date__c=date.today().addMonths(-10);
        emp1.Role__c='HR';
        emp1.EmployeeNo__c='emp124';
        emp1.Employee_State__c='Andhra Pradesh';
        emp1.Aadhar_Number__c='145623209835';
        emp1.Account_Number__c='123456889985';
        emp1.Employee_Id__c='CT-8747';
        emp1.IFSC_Code__c='SBIN0123458';
        emp1.MobilePhone='9614123128';
        emp1.Phone='9614123125';
        emp1.PAN_Number__c='MJAPS1145K';
        emp1.PU_DU__c=du1.id;
        emp1.Email='guestuser1@gmail.com';
        emp1.Designation__c = 'None';
        emp1.Band__c = 'Band C';
        emp.Appraiser__c = empl.Id;
        emp1.Reviewer__c = emp.Id;
        insert emp1;
        
        Evaluation__c evaluation = new Evaluation__c();
        evaluation.Status__c = 'Pending with Reviewer';
        evaluation.Name = 'Madhav Appraisal';
        evaluation.AppraiserFeedback__c = 'Appraisal Completed';
        evaluation.AppraiserRating__c = 3;
        evaluation.EmployeeMaster__c = emp.Id;
        insert evaluation;
    }
    
    @isTest
    public static void getAppraiserRecordsTest(){
        Contact emp = [Select Id, Name from Contact limit 1];
        Evaluation__c evaluation = [Select Id, Name,Status__c from Evaluation__c Limit 1];
        evaluation.Status__c = 'Submitted';
        update evaluation;
        system.debug(evaluation);
        CCT_AppraiserController.getAppraiserRecords(emp.Id);
        CCT_AppraiserController.getAppraiserRecord(evaluation.Id);
        CCT_AppraiserController.getAllAppraiserRecords(emp.Id);
        CCT_AppraiserController.getAppraiserStatusRecordCounts(emp.Id);
    }
    
    @isTest
    public static void getEndDate(){
        Appraisal_Cycles__mdt appraisalEndDate = [Select Id, End_Date__c, Appraisal_Cycle_Name__c, Label, MasterLabel,DeveloperName from Appraisal_Cycles__mdt where DeveloperName = 'Annual_6'];
        CCT_AppraiserController.getAppraiserEndDate();
    }
    @isTest
    public static void TryAndCatchTest(){
        Contact emp = [Select Id, Name from Contact limit 1];
        Evaluation__c evaluation = [Select Id, Status__c from Evaluation__c Limit 1];
        evaluation.Status__c = 'Auto Submitted';
        update evaluation;
        system.debug(evaluation);
        try{
            CCT_AppraiserController.getAppraiserRecords(emp.Id);
            CCT_AppraiserController.getAppraiserRecord(evaluation.Id);
            CCT_AppraiserController.getAllAppraiserRecords(emp.Id);
            CCT_AppraiserController.getAppraiserStatusRecordCounts(emp.Id);
            CCT_AppraiserController.fetchAppraisalForm(emp.Id);
            CCT_AppraiserController.updateAppraisalFormStatus(emp.Id);
            CCT_AppraiserController.calculateSumOfTask(emp.Id);
        } catch (Exception ex){
            
        } }
    
    @isTest
    public static void fetchTermCycleRecordsTest() {
        Contact emp = [SELECT Id FROM Contact LIMIT 1];
        List<Evaluation__c> annualCycleRecords = CCT_AppraiserController.fetchTermCycleRecords(emp.Id, 'AnnualCycle');
        List<Evaluation__c> midTermCycleRecords = CCT_AppraiserController.fetchTermCycleRecords(emp.Id, 'MidTermCycle');    }
    
    @isTest
    public static void getAppraiseeListTest() {
        Contact emp = [SELECT Id FROM Contact LIMIT 1];
        List<Contact> appraiseeListAppraiser = CCT_AppraiserController.getAppraiseeList(emp.Id, 'appraiser');
        List<Contact> appraiseeListReviewer = CCT_AppraiserController.getAppraiseeList(emp.Id, 'reviewer');
    }
    @isTest
    public static void updateRecordTest() {
        Evaluation__c evaluation = new Evaluation__c();
        evaluation.Status__c = 'Auto Submitted';
        evaluation.AppraiserFeedback__c = 'Sample Feedback';
        evaluation.AppraisalCycle__c = 'AnnualCycle';
        insert evaluation;
        evaluation.AppraiserFeedback__c = 'Updated Feedback';
        Test.startTest();
        String result = CCT_AppraiserController.updateRecord(evaluation);
        Test.stopTest();
        Evaluation__c updatedEvaluation = [SELECT AppraiserFeedback__c FROM Evaluation__c WHERE Id = :evaluation.Id];
    }
    @isTest
    public static void calculateSumOfTaskTest() {
        
        Evaluation__c evaluation = new Evaluation__c();
        insert evaluation;
        Task_Tracker__c task1 = new Task_Tracker__c();
        task1.Evaluation__c = evaluation.Id;
        task1.Appraiser_Weightage_for_Each_KPIs__c = 5;
        insert task1;
        
        Task_Tracker__c task2 = new Task_Tracker__c();
        task2.Evaluation__c = evaluation.Id;
        task2.Appraiser_Weightage_for_Each_KPIs__c = 8;
        insert task2;
        Test.startTest();
        Double totalWeightage = CCT_AppraiserController.calculateSumOfTask(evaluation.Id);
        Test.stopTest();
    }
      @isTest
    public static void updateAppraisalFormStatusTest() {
        Evaluation__c evaluation = new Evaluation__c();
        evaluation.Status__c = 'Submitted';
        insert evaluation;
        Test.startTest();
        CCT_AppraiserController.updateAppraisalFormStatus(evaluation.Id);
        Test.stopTest();
        Evaluation__c updatedEvaluation = [SELECT Id, Status__c FROM Evaluation__c WHERE Id = :evaluation.Id];
        evaluation.Status__c = 'Auto Submitted';
        update evaluation;
       // Test.startTest();
        CCT_AppraiserController.updateAppraisalFormStatus(evaluation.Id);
       // Test.stopTest();
        updatedEvaluation = [SELECT Id, Status__c FROM Evaluation__c WHERE Id = :evaluation.Id];
    }
}