force-app/main/default/objects/Appraisal_Cycles__mdt.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Cycle_Name__c</fullName>
        <label>Appraisal Cycle Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cycle__c</fullName>
        <label>Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MidTermCycle</fullName>
                    <label>Mid Term Cycle</label>
                </value>
                <value>
                    <fullName>AnnualCycle</fullName>
                    <label>Annual Cycle</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Appraisal Cycles</label>
    <pluralLabel>Appraisal Cycles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AppraisalCycle__c</fullName>
        <label>Appraisal Cycle</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Appraiser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Appraiser</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Employee Master (Appraiser)</relationshipLabel>
        <relationshipName>Employee_Master1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Band__c</fullName>
        <label>Band</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Band B</fullName>
                </value>
                <value>
                    <fullName>Band C</fullName>
                </value>
                <value>
                    <fullName>Band E</fullName>
                </value>
                <value>
                    <fullName>Band M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Designation__c</fullName>
        <label>Designation</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Band__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>ASSOCIATE CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>ASSOCIATE DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>ASSOCIATE MANAGER</fullName>
                </value>
                <value>
                    <fullName>AVP(ASSOCIATE VICE PRESIDENT)</fullName>
                </value>
                <value>
                    <fullName>CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>DIRECTOR - HUMAN RESOURCES</fullName>
                </value>
                <value>
                    <fullName>EXECUTIVE</fullName>
                </value>
                <value>
                    <fullName>EXECUTIVE VP</fullName>
                </value>
                <value>
                    <fullName>GROUP PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>GROUP QA MANAGER</fullName>
                </value>
                <value>
                    <fullName>INDUSTRY PRINCIPAL</fullName>
                </value>
                <value>
                    <fullName>LEAD CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>MANAGEMENT TRAINEE</fullName>
                </value>
                <value>
                    <fullName>MANAGER</fullName>
                </value>
                <value>
                    <fullName>PRINCIPAL CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>PRINCIPAL TECHNOLOGY ARCHITECT</fullName>
                </value>
                <value>
                    <fullName>PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>QA LEAD</fullName>
                </value>
                <value>
                    <fullName>QA MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>SENIOR DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>SENIOR EXECUTIVE</fullName>
                </value>
                <value>
                    <fullName>SENIOR INDUSTRY PRINCIPAL</fullName>
                </value>
                <value>
                    <fullName>SENIOR LEAD CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>SENIOR MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR QA LEAD</fullName>
                </value>
                <value>
                    <fullName>SENIOR QA MANAGER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Experience_in_Cloudtaru__c</fullName>
        <formula>(MONTH(TODAY()) + (12*(YEAR(TODAY())-YEAR(Employee_Joining_Date__c))) - MONTH(Employee_Joining_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Experience in Cloudtaru</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>AppraisalCycle__c</fullName>
        <label>Appraisal Cycle</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AppraiserName__c</fullName>
        <formula>EmployeeMaster__r.Appraiser__r.FirstName +&apos; &apos;+ EmployeeMaster__r.Appraiser__r.LastName</formula>
        <label>Appraiser Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmployeeMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Master</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Not Initiated</fullName>
                </value>
                <value>
                    <fullName>Pending with Reviewer</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submitted by Appraiser</fullName>
                </value>
                <value>
                    <fullName>Final Rating Available</fullName>
                </value>
                <value>
                    <fullName>Grievance Raised</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Auto Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Band__c</fullName>
        <label>Band</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Band B</fullName>
                </value>
                <value>
                    <fullName>Band C</fullName>
                </value>
                <value>
                    <fullName>Band E</fullName>
                </value>
                <value>
                    <fullName>Band M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Designation__c</fullName>
        <label>Designation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASSOCIATE CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>ASSOCIATE DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>ASSOCIATE MANAGER</fullName>
                </value>
                <value>
                    <fullName>AVP(ASSOCIATE VICE PRESIDENT)</fullName>
                </value>
                <value>
                    <fullName>CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>DIRECTOR - HUMAN RESOURCES</fullName>
                </value>
                <value>
                    <fullName>EXECUTIVE</fullName>
                </value>
                <value>
                    <fullName>EXECUTIVE VP</fullName>
                </value>
                <value>
                    <fullName>GROUP PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>GROUP QA MANAGER</fullName>
                </value>
                <value>
                    <fullName>INDUSTRY PRINCIPAL</fullName>
                </value>
                <value>
                    <fullName>LEAD CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>MANAGEMENT TRAINEE</fullName>
                </value>
                <value>
                    <fullName>MANAGER</fullName>
                </value>
                <value>
                    <fullName>PRINCIPAL CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>PRINCIPAL TECHNOLOGY ARCHITECT</fullName>
                </value>
                <value>
                    <fullName>PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>QA LEAD</fullName>
                </value>
                <value>
                    <fullName>QA MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>SENIOR DIRECTOR</fullName>
                </value>
                <value>
                    <fullName>SENIOR EXECUTIVE</fullName>
                </value>
                <value>
                    <fullName>SENIOR INDUSTRY PRINCIPAL</fullName>
                </value>
                <value>
                    <fullName>SENIOR LEAD CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>SENIOR MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR PROJECT MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR QA LEAD</fullName>
                </value>
                <value>
                    <fullName>SENIOR QA MANAGER</fullName>
                </value>
                <value>
                    <fullName>SENIOR QUALITY ANALYST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EmployeeMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Master</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Task tracker (Employee Master)</relationshipLabel>
        <relationshipName>Task_tracker2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Evaluation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluation</label>
        <referenceTo>Evaluation__c</referenceTo>
        <relationshipLabel>Task tracker</relationshipLabel>
        <relationshipName>Task_tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Testing In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing completed</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task Tracker</label>
    <nameField>
        <displayFormat>TQ-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task tracker</pluralLabel>
    <recordTypes>
        <fullName>AppraiseeTasks</fullName>
        <active>true</active>
        <label>Appraisee Tasks</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CCT_AppraiseeController_Batch.cls
public class CCT_AppraiseeController_Batch implements Database.Batchable<sObject>,Database.Stateful  {
    /***
@author Sneha
@description Batch Apex start Method
@return null
@date 10/04/2023
**/
    
    public boolean isEligible =false;
    public boolean endDateAppraisee = false;
    public Date startDate;
    public Date endDate;
    public String cycleName;
    public String cycle;
    Map<Integer,String> month = new Map<Integer,String>{1=>'Jan',2=>'Feb',3=>'Mar',4=>'Apr',5=>'May',
        6=>'Jun',7=>'Jul',8=>'Aug',9=>'Sep',10=>'Oct',11=>'Nov',
        12=>'Dec'};
            public Database.QueryLocator start(Database.BatchableContext batch){
                List<String> cycles = new List<String>{CCT_Kriya_Constants.MIDTERMCYCLE,CCT_Kriya_Constants.ANNUALTERMCYCLE,CCT_Kriya_Constants.MIDTERMAPPRAISEE_TO_APPRAISER,CCT_Kriya_Constants.ANNUALTERMAPPRAISEE_TO_APPRAISER};
                    List<Appraisal_Cycles__mdt> cycleRecords = [SELECT Appraisal_Cycle_Name__c,End_Date__c,Stage__c,Start_Date__c,MasterLabel,Cycle__c
                                                                FROM Appraisal_Cycles__mdt WHERE MasterLabel IN : cycles WITH SECURITY_ENFORCED];
                system.debug(cycleRecords);
                for(Appraisal_Cycles__mdt record : cycleRecords ){ 
                    system.debug(record.Start_Date__c);
                    if( (record.MasterLabel == CCT_Kriya_Constants.MIDTERMCYCLE || record.MasterLabel == CCT_Kriya_Constants.ANNUALTERMCYCLE) && record.Start_Date__c == system.today()){
                        isEligible = true;
                        startDate = record.Start_Date__c; 
                        endDate = record.End_Date__c;
                        cycleName = month.get(startDate.month())+'\''+startDate.year()+'-'+month.get(endDate.month())+'\''+endDate.year();
                        cycle = record.Cycle__c;
                    } else if( (record.MasterLabel == CCT_Kriya_Constants.MIDTERMAPPRAISEE_TO_APPRAISER || record.MasterLabel == CCT_Kriya_Constants.ANNUALTERMAPPRAISEE_TO_APPRAISER) && record.End_Date__c == system.today()){
                        endDateAppraisee = true;
                    }    
                }
                Integer lastmonths = Integer.valueOf(Label.Minimum_Required_No_of_Months);
                String isEligiblequery = 'SELECT Id, Employee_Joining_Date__c, Name, AppraisalCycle__c, Designation__c, Band__c FROM Contact WHERE Designation__c !=NULL AND Band__c!=NULL AND Employee_Joining_Date__c !=NULL AND Appraiser__c!= NULL AND Experience_in_Cloudtaru__c >=: lastmonths WITH SECURITY_ENFORCED';
                system.debug(isEligiblequery);
               // if(isEligible || endDateAppraisee){
                    return Database.getQueryLocator(isEligiblequery);            
               // }
               // return null;    
            }
    /***
@author Sneha
@description Batch Apex execute Method
@List of contacts
@date 10/04/2023
**/
    public void execute(Database.BatchableContext batch, List<Contact> conLst){
        try {
            
            Map<Map<String, String>,List<string>> emailTemplateMap = new Map<Map<String, String>,List<string>>();
            List<Evaluation__c> recordsToInsert = new List<Evaluation__c>();
            List<Contact> recordsToUpdate = new List<Contact>();
            List<Evaluation__c> appraiseRecords = new List<Evaluation__c>();
            Id recordTypeId =Schema.SObjectType.Evaluation__c.getRecordTypeInfosByDeveloperName().get(CCT_Kriya_Constants.RECORDTYPE).getRecordTypeId();
            Set<String> contactIds = new Set<String>();
            for(Contact con : conLst){
                contactIds.add(con.Id);
            }
            if(endDateAppraisee){
                List<String> status = new List<String>{CCT_Kriya_Constants.INITIATED_STATUS, CCT_Kriya_Constants.NOTINITIATED_STATUS};
                    List<Evaluation__c> initiatedRecords = [SELECT Id,Status__c,EmployeeMaster__c ,AppraiserName__c,EmployeeMaster__r.Name,
                                                            EmployeeMaster__r.Email,IsAutoSubmit__c
                                                            FROM  Evaluation__c 
                                                            WHERE EmployeeMaster__c IN : contactIds 
                                                            AND Status__c IN : status
                                                            AND RecordTypeId =:recordTypeId];
                List<Evaluation__c> notInitiatedRecords = new List<Evaluation__c>();
                for(Evaluation__c  rec: initiatedRecords){
                    if(rec.Status__c == CCT_Kriya_Constants.NOTINITIATED_STATUS){
                        notInitiatedRecords.add(rec);
                    }
                    rec.Status__c = CCT_Kriya_Constants.AUTOSUBMITTED_STATUS;//CCT_Kriya_Constants.SUBMITTED_STATUS 
                    rec.IsAutoSubmit__c = true;
                    rec.SubmittedDate__c = system.today();
                }
                
                // Create task tracker records with Appraisee RecordType and weightages as 100%
                List<Task_Tracker__c> taskTrackerRecords = new List<Task_Tracker__c>();
                Id appraiseeRecordTypeId = Schema.SObjectType.Task_Tracker__c.getRecordTypeInfosByDeveloperName().get('AppraiseeTasks').getRecordTypeId();
                
                for (Evaluation__c appraisal : notInitiatedRecords) {
                    Task_Tracker__c taskTracker = new Task_Tracker__c(
                        Evaluation__c = appraisal.Id,
                        RecordTypeId = appraiseeRecordTypeId,
                        Employee_Name__c = appraisal.EmployeeMaster__c,
                        MinWeightage__c = 100,
                        MaxWeightage__c = 100,
                        KPICategory__c = 'Functional',
                        KPI_Name__c = 'InTime Delivery',
                        Justification__c = 'This appraisal form is Auto Submitted',
                        Challenges__c =  'This appraisal form is Auto Submitted',
                        // SelfRating__c=0,
                        Weightage__c =100
                    );
                    taskTrackerRecords.add(taskTracker);
                }
                if(taskTrackerRecords != null && taskTrackerRecords.size()>0){
                    Database.insert(taskTrackerRecords, false); 
                }
                //update initiatedRecords;
                //     SObjectAccessDecision securityDecision = Security.stripInaccessible( AccessType.UPDATABLE, initiatedRecords);
                //     update securityDecision.getRecords();
                List<database.Saveresult> updateresults = new List<database.Saveresult>();
                if(initiatedRecords != null && initiatedRecords.size()>0){
                    updateresults=database.Update(initiatedRecords, false);
                }
                
                System.debug('initiatedRecords :: ' +initiatedRecords);
                if (updateResults[0].isSuccess()) 
                { 
                    //   List<String> emailList = new List<String>(); // Add email recipients
                    
                    
                    // Trigger email notification here Auto-Submitted to Appraiser
                    for(Evaluation__c  appraisal: initiatedRecords){
                        Map<String, String> fieldValuesMap = new Map<String, String>();  
                        List<String> emailRecList = new List<String>(); // Add email recipients
                        fieldValuesMap.put('KeySet', appraisal.Id+' KeySet');
                        fieldValuesMap.put('AppraiserName', appraisal.AppraiserName__c);
                        fieldValuesMap.put('AppraiseeName',appraisal.EmployeeMaster__r.Name);
                        fieldValuesMap.put('TriggerName','Auto_Submitted_to_Appraiser');
                        emailRecList.add(appraisal.EmployeeMaster__r.Email);
                        emailTemplateMap.put(fieldValuesMap,emailRecList);
                        //  listTemplateMap.add(emailTemplateMap);
                        system.debug('EmailTemplateMap'+emailTemplateMap);
                    }   
                    CCT_PMS_EmailTemplateFramework.sendCustomNotification(emailTemplateMap);
                }     
            } else if(isEligible){ 
                //  system.debug('Arc'); 
                for(Contact con : conLst){
                    Contact contactRec = new Contact(Id=con.Id,AppraisalCycle__c=cycle);
                    Evaluation__c evaluation = new Evaluation__c(Name=con.Name+'   '+cycleName,recordTypeId = recordTypeId,Status__c = CCT_Kriya_Constants.NOTINITIATED_STATUS ,
                                                                 EmployeeMaster__c=con.Id, Start_Date__c = startDate,End_Date__c= endDate,AppraisalCycle__c=cycle);
                    recordsToInsert.add(evaluation);
                    recordsToUpdate.add(contactRec);
                    system.debug(contactRec);
                    system.debug(evaluation);
                    //appraiseRecords.add(evaluation); 
                }
                // system.debug(recordsToUpsert);
                if((recordsToInsert!=null && !recordsToInsert.isEmpty()) && (recordsToUpdate!=null && !recordsToUpdate.isEmpty())){
                    //    SObjectAccessDecision securityDecision = Security.stripInaccessible( AccessType.UPSERTABLE,recordsToUpsert);
                    //  upsert securityDecision.getRecords();
                    // system.debug('104'+recordsToUpsert);
                    List<Database.SaveResult> insertResults = Database.insert(recordsToInsert, false);
                    List<Database.SaveResult> updateResults = Database.update(recordsToUpdate, false);
                    
                    List<Evaluation__c> newlyCreatedRecords=[Select Id,EmployeeMaster__r.Email, EmployeeMaster__r.Appraiser__r.Email,EmployeeMaster__r.Reviewer__r.Email,Start_Date__c,End_Date__c from Evaluation__c where Status__c = :CCT_Kriya_Constants.NOTINITIATED_STATUS and Start_Date__c = :startDate and End_Date__c= :endDate and AppraisalCycle__c=:cycle ];
                    System.debug('106:Size'+updateResults.size());
                    System.debug('107:Size'+updateResults);
                    if (insertResults[0].isSuccess()) {
                        // system.debug('109'+recordsToUpsert);
                        System.debug('newlyCreatedRecords size :: ' +newlyCreatedRecords.size());
                        // Trigger email notification here for each Evaluation__c record  Appraisal Not Initiated
                        for (Evaluation__c appraisal : newlyCreatedRecords) {
                            System.debug('114:Appraisal Names:'+appraisal);
                            List<String> emailList = new List<String>(); 
                            Map<String, String> fieldValuesMap = new Map<String, String>();
                            fieldValuesMap.put('KeySet', appraisal.Id);
                            fieldValuesMap.put('StartDate', String.valueOf(appraisal.Start_Date__c));
                            fieldValuesMap.put('EndDate', String.valueOf(appraisal.End_Date__c));
                            fieldValuesMap.put('TriggerName','Notification_to_Appraisee');
                            
                            emailList.add(appraisal.EmployeeMaster__r.Email);
                            /* if(appraisal.EmployeeMaster__r.Appraiser__c!=null){
emailList.add(appraisal.EmployeeMaster__r.Appraiser__r.Email);
}
if(appraisal.EmployeeMaster__r.Reviewer__c!=null){
emailList.add(appraisal.EmployeeMaster__r.Reviewer__r.Email);
}*/
                            emailTemplateMap.put(fieldValuesMap,emailList);
                            System.debug('122: Email List:'+emailList);
                            // CCT_PMS_EmailTemplateFramework.sendCustomNotification(emailTemplateMap);
                            // CCT_PMS_EmailTemplateFramework.sendCustomNotification('Notification to Appraisee', emailList, fieldValuesMap);
                        }
                        CCT_PMS_EmailTemplateFramework.sendCustomNotification(emailTemplateMap);
                    }
                    
                }
            }
            
            system.debug('sa'+emailTemplateMap);
        } catch(Exception e) {
            // system.debug(e.getMessage());
        }
    }
    /***
@author Sneha
@description Batch Apex finish Method
@date 10/04/2023
**/
    public void finish(Database.BatchableContext batch){ 
        
    }
    
}