force-app/main/default/objects/Appraisal_Cycles__mdt.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Cycle_Name__c</fullName>
        <label>Appraisal Cycle Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>Appraisal Cycles</label>
    <pluralLabel>Appraisal Cycles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AppraisalCycle__c</fullName>
        <label>Appraisal Cycle</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Appraiser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Appraiser</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Employee Master (Appraiser)</relationshipLabel>
        <relationshipName>Employee_Master1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Employee Master (Reviewer)</relationshipLabel>
        <relationshipName>Employee_Master2</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/default/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>AppraisalCycle__c</fullName>
        <label>Appraisal Cycle</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AppraiserComments__c</fullName>
        <label>Appraiser Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AppraiserFeedback__c</fullName>
        <label>Appraiser Feedback</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AppraiserName__c</fullName>
        <formula>EmployeeMaster__r.Appraiser__r.FirstName +&apos; &apos;+ EmployeeMaster__r.Appraiser__r.LastName</formula>
        <label>Appraiser Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AppraiserRating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Appraiser Rating</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApraiseeOverallRating__c</fullName>
        <label>Apraisee Overall Rating</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ConflictFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Conflict Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EligibilityForPromotion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligibility For Promotion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EmployeeMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Master</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Evaluations</relationshipLabel>
        <relationshipName>Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsAutoSubmit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsAutoSubmit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JustificationForEligibility__c</fullName>
        <label>Justification For Eligibility</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OverallComments__c</fullName>
        <label>Overall Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OverallRating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Overall Rating</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PRDDateAndTime__c</fullName>
        <label>PRD Date And Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PRDDuration__c</fullName>
        <label>PRD Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRDWithAppraiserIsDone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PRD With Appraiser Is Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PRD_Date_And_Time_Appraiser__c</fullName>
        <label>PRD Date And Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PRD_Duration_Appraiser__c</fullName>
        <label>PRD Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRD_With_Appraisee_Is_Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PRD With Appraisee Is Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReviewerFeedback__c</fullName>
        <label>Reviewer Feedback</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReviewerName__c</fullName>
        <formula>EmployeeMaster__r.Reviewer__r.FirstName +&apos; &apos;+ EmployeeMaster__r.Reviewer__r.LastName</formula>
        <label>Reviewer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReviewerRating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reviewer Rating</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Not Initiated</fullName>
                </value>
                <value>
                    <fullName>Pending with Reviewer</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submitted by Appraiser</fullName>
                </value>
                <value>
                    <fullName>Final Rating Available</fullName>
                </value>
                <value>
                    <fullName>Grievance Raised</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Auto Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubmittedDate__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WhatCanBeDoneBetter__c</fullName>
        <label>What Can Be Done Better/Improvement Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WhatHappenedWell__c</fullName>
        <label>What Happened Well</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CCT_PMSReviewer.cls
/**
 * @author PMSDev02
 * @description class to handle the CCT_PMSReviewer records.
 * @date 11/04/2023
 */
public without sharing class CCT_PMSReviewer {
    /**
    * @description Method to getReviewerRecords.
    * @param employeeId string
    * @return List<Evaluation__c>
    */
    @AuraEnabled
    public static List<Evaluation__c> getReviewerRecords(string employeeId){
        List<Evaluation__c> evaluationData = [SELECT 
        Id, Name, AppraiserFeedback__c, AppraiserName__c, AppraiserComments__c, AppraisalCycle__c, ReviewerName__c, AppraiserRating__c,ConflictFlag__c,EligibilityForPromotion__c,EmployeeMaster__c, EmployeeMaster__r.Name,
        JustificationForEligibility__c, OverallComments__c, OverallRating__c, PRDDateAndTime__c, PRDWithAppraiserIsDone__c,
        ReviewerFeedback__c, ReviewerRating__c, Status__c, SubmittedDate__c, WhatCanBeDoneBetter__c, WhatHappenedWell__c 
        FROM Evaluation__c where Status__c = 'Pending with Reviewer' and EmployeeMaster__r.Reviewer__c = :employeeId ];

        return evaluationData;
    }

    /**
    * @description Method to getAppraisalRecord.
    * @param recordId string
    * @return Evaluation__c
    */
    @AuraEnabled(cacheable = true)
    public static Evaluation__c getAppraisalRecord(string recordId){
        Evaluation__c evaluationData = [SELECT 
        Id, Name, AppraiserFeedback__c, AppraiserName__c, AppraiserComments__c, AppraisalCycle__c, ReviewerName__c, AppraiserRating__c,ConflictFlag__c,EligibilityForPromotion__c,EmployeeMaster__c, EmployeeMaster__r.Name,
        JustificationForEligibility__c, OverallComments__c, OverallRating__c, PRDDateAndTime__c, PRDDuration__c, PRDWithAppraiserIsDone__c,
        ReviewerFeedback__c, ReviewerRating__c, Status__c, SubmittedDate__c, WhatCanBeDoneBetter__c, WhatHappenedWell__c,
        PRD_Date_And_Time_Appraiser__c, PRD_Duration_Appraiser__c, PRD_With_Appraisee_Is_Done__c, ApraiseeOverallRating__c 
        FROM Evaluation__c where Status__c = 'Pending with Reviewer' and Id = :recordId ];

        return evaluationData;
    }

    /**
    * @description Method to getAllAppraisalRecords.
    * @param employeeId string
    * @return List<Evaluation__c>
    */
    @AuraEnabled
    public static List<Evaluation__c> getAllAppraisalRecords(string employeeId){
        List<Evaluation__c> evaluationData = [SELECT 
        Id, Name, AppraiserFeedback__c, AppraiserName__c, AppraisalCycle__c, ReviewerName__c, AppraiserRating__c,ConflictFlag__c,EligibilityForPromotion__c,EmployeeMaster__c, EmployeeMaster__r.Name,
        JustificationForEligibility__c, OverallComments__c, OverallRating__c, PRDDateAndTime__c, PRDDuration__c, PRDWithAppraiserIsDone__c,
        ReviewerFeedback__c, ReviewerRating__c, Status__c, SubmittedDate__c, WhatCanBeDoneBetter__c, WhatHappenedWell__c,
        PRD_Date_And_Time_Appraiser__c, PRD_Duration_Appraiser__c, PRD_With_Appraisee_Is_Done__c, ApraiseeOverallRating__c
        FROM Evaluation__c where EmployeeMaster__r.Reviewer__c = :employeeId ];

        return evaluationData;
    }

    /**
    * @description Method to getAppraisalStatusRecordCounts.
    * @param employeeId string
    * @return AggregateResult[]
    */
    @AuraEnabled(cacheable = true)
    public static AggregateResult[] getAppraisalStatusRecordCounts(string employeeId){
        AggregateResult[] statusCounts = [select COUNT(ID) statusCount, Status__c from Evaluation__c where Status__c !='' and EmployeeMaster__r.Reviewer__c = :employeeId  group by Status__c];
        return statusCounts;
    }

    /**
    * @description Method to getAppraisalEndDate.
    * @return Appraisal_Cycles__mdt
    */
    @AuraEnabled(cacheable = true)
    public static Appraisal_Cycles__mdt getAppraisalEndDate(){
        Appraisal_Cycles__mdt appraisalEndDate = [Select Id, End_Date__c, Appraisal_Cycle_Name__c, Label, MasterLabel,DeveloperName from Appraisal_Cycles__mdt where DeveloperName = 'Annual_6' ];
        return appraisalEndDate;
    }

    /**
    * @description Method to getEmployeeRecord.
    * @param employeeId string
    * @return Contact
    */
    @AuraEnabled(cacheable = true)
    public static List<Contact> getEmployeeRecord(string employeeId){
        List<Contact> employee = [SELECT Id, Name, (SELECT Id from Employee_Master1__r limit 1), (SELECT Id from Employee_Master2__r limit 1 ) from Contact where Id = :employeeId ];
        return employee;
    }

    /**
     * @date 25/04/2023
     * @description Method to updateAppraisal.
     * @param recordId String
     * @param overallRating Double
     * @param overallComments String
     * @param eligibilityForPromotion boolean
     * @return Evaluation__c
     */
    @AuraEnabled
    public static Evaluation__c updateAppraisal(string recordId, Double overallRating, string overallComments, boolean eligibilityForPromotion){
        Evaluation__c evaluationRecord = new Evaluation__c();
        evaluationRecord.Id = recordId;
        evaluationRecord.OverallRating__c = overallRating;
        evaluationRecord.OverallComments__c= overallComments;
        evaluationRecord.EligibilityForPromotion__c = eligibilityForPromotion;
        update evaluationRecord;
        return evaluationRecord;
    }

        /**
     * @date 25/04/2023
     * @description Method to finalizeAppraisal.
     * @param recordId String
     */
    @AuraEnabled
    public static void finalizeAppraisal(string recordId){
        //Evaluation__c evaluationRecord = new Evaluation__c();
        Evaluation__c evaluationRecord = [SELECT Id, Status__c, ReviewerName__c,End_Date__c,EmployeeMaster__r.Email,EmployeeMaster__r.Name FROM Evaluation__c WHERE Id =:recordId];
        List<string> emailList = new List<string>();
        evaluationRecord.Id = recordId;
        evaluationRecord.Status__c = 'Final Rating Available';
        //update evaluationRecord;

        List<database.Saveresult> updateResults =database.Update(new list<evaluation__c>{evaluationRecord}, false);
        if (updateResults[0].isSuccess()) 
        {
            Map<Map<String, String>,List<string>> emailTemplateMap = new Map<Map<String, String>,List<string>>(); 
            map<string,string> mergeFieldsData = new map<string,string>();
            mergeFieldsData.put('KeySet', evaluationRecord.Id);
            mergeFieldsData.put('ReviewerName', evaluationRecord.ReviewerName__c);
            mergeFieldsData.put('AppraiseeName',evaluationRecord.EmployeeMaster__r.Name);
            mergeFieldsData.put('TriggerName','Final_Rating_Availabl_Template');
            //mergeFieldsData.put('EndDate', string.valueOf(evaluationRecord.End_Date__c));
            emailList.add(evaluationRecord.EmployeeMaster__r.Email);
            emailTemplateMap.put(mergeFieldsData,emailList);
            system.debug('EmailTemplateMap'+emailTemplateMap);
            CCT_PMS_EmailTemplateFramework.sendCustomNotification(emailTemplateMap);
         
            //CCT_PMS_EmailTemplateFramework.sendCustomNotification('Final Rating Available',emailList,mergeFieldsData);//TRigger Nane
        } 
        else 
        { 
            System.debug('Record failed to update. Error message: ' + updateResults[0].getErrors()[0].getMessage());
        }
    }

    /**
    * @description Method to getIndividualAppraisalRecord.
    * @param recordId string
    * @return Evaluation__c
    */
    @AuraEnabled
    public static Evaluation__c getIndividualAppraisalRecord(string recordId){
        Evaluation__c evaluationData = [SELECT 
        Id, Name, AppraiserFeedback__c, AppraiserName__c, AppraiserComments__c, ReviewerName__c, AppraisalCycle__c, AppraiserRating__c,ConflictFlag__c,EligibilityForPromotion__c,EmployeeMaster__c, EmployeeMaster__r.Name,
        JustificationForEligibility__c, OverallComments__c, OverallRating__c, PRDDateAndTime__c, PRDDuration__c, PRDWithAppraiserIsDone__c,
        ReviewerFeedback__c, ReviewerRating__c, Status__c, SubmittedDate__c, WhatCanBeDoneBetter__c, WhatHappenedWell__c,
        PRD_Date_And_Time_Appraiser__c,IsAutoSubmit__c, PRD_Duration_Appraiser__c, PRD_With_Appraisee_Is_Done__c, ApraiseeOverallRating__c 
        FROM Evaluation__c where Id = :recordId ];

        return evaluationData;
    }

}