force-app/main/default/objects/Evaluation__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Not Initiated</fullName>
                </value>
                <value>
                    <fullName>Pending with Reviewer</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submitted by Appraiser</fullName>
                </value>
                <value>
                    <fullName>Final Rating Available</fullName>
                </value>
                <value>
                    <fullName>Grievance Raised</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Auto Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMS_KPI_Fields__mdt.object
<CustomObject>
    <fields>
        <fullName>Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieldAPI__c</fullName>
        <label>FieldAPI</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldLabel__c</fullName>
        <label>FieldLabel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mandatory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mandatory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ObjectAPI__c</fullName>
        <label>ObjectAPI</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Picklist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextArea__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TextArea</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Text</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserRole__c</fullName>
        <label>UserRole</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>PMS KPI Fields</label>
    <pluralLabel>PMS KPI Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Task_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Evaluation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Evaluation</label>
        <referenceTo>Evaluation__c</referenceTo>
        <relationshipLabel>Task tracker</relationshipLabel>
        <relationshipName>Task_tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mandatory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mandatory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Testing In Progress</fullName>
                </value>
                <value>
                    <fullName>Testing completed</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Task Tracker</label>
    <nameField>
        <displayFormat>TQ-{0000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task tracker</pluralLabel>
    <recordTypes>
        <fullName>AppraiseeTasks</fullName>
        <active>true</active>
        <label>Appraisee Tasks</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CCT_KPICustomMetadata.cls
/**
* @description 
*/
public without sharing class CCT_KPICustomMetadata {

    /**
    * @description getKPICustomMetadata
    * @param userRole string
    * @param status string
    * @return PMS_KPI_Fields__mdt
    **/
    @AuraEnabled(cacheable=true)
    public static List<PMS_KPI_Fields__mdt> getKPICustomMetadata(string userRole, string status)
    {
        List<PMS_KPI_Fields__mdt> kpiList = [Select Id, Label, FieldLabel__c, Sequence__c, FieldAPI__c, Editable__c, ObjectAPI__c, UserRole__c, Status__c,  Mandatory__c, Checkbox__c, Picklist__c, Text__c, Date__c, TextArea__c
        from PMS_KPI_Fields__mdt where UserRole__c=:userRole and Status__c=:status order by Sequence__c];
        return kpiList;
    }


    /**
    * @description getCategoryData
    * @param userRole string
    * @param status string
    * @param evaluationId Id
    * @return list<Task_Tracker__c>
    **/
    @AuraEnabled
    public static list<Task_Tracker__c> getKpiData(string userRole, string status, Id evaluationId)
    {
        //Get the recordtype Id
        Id recordTypeId = Schema.SObjectType.Task_Tracker__c.getRecordTypeInfosByDeveloperName().get('AppraiseeTasks').getRecordTypeId();
        List<PMS_KPI_Fields__mdt> kpiFieldList = [Select Id, Label, FieldLabel__c, Sequence__c, FieldAPI__c, Editable__c, ObjectAPI__c, UserRole__c, Status__c,  Mandatory__c, Checkbox__c, Picklist__c, Text__c, Date__c, TextArea__c
        from PMS_KPI_Fields__mdt where UserRole__c=:userRole and Status__c=:status order by Sequence__c];
        
        List<string> fieldsToFetch = new List<string>();
        for(PMS_KPI_Fields__mdt kfl : kpiFieldList) 
        {
            string fieldName = kfl.FieldAPI__c;
            fieldsToFetch.add(fieldName);
        }

        string fieldList = '';
        for(string str : fieldsToFetch)
        {
            fieldList += str+',';
        }
        
        // remove last additional comma from string
        fieldList = fieldList.removeEnd(',');

        list<Task_Tracker__c> queryResult;
        string condition = 'Where Evaluation__c=:evaluationId and recordtypeId=:recordTypeId';
        string sobj = 'Task_Tracker__c';
        string soqlQuery = 'Select ' +fieldList+ ' from ' +sobj+ ' ' +condition;
        queryResult = Database.query(soqlQuery);
        return queryResult;
    }
}